/// @file: BLNetwork.h
///
/// The basic design for the sockets implementation is built around
/// an object that performs all transactions asynchronously.  There is a
/// blocking version of the socket that is implemented in terms of the 
/// asynchronous object.
/// 
/// The MIT License(MIT)
/// @copyright 2014 Paul M Watt
///
///
/// Additional Copyright information. 
/// This socket abstraction is adapted from Boost::ASIO, asynchronous I/O library.
///
/// ASIO Author: Copyright Chris Kohlhoff
/// The software is published under the Boost Software License:
///
/// Boost Software License - Version 1.0 - August 17th, 2003
/// 
/// Permission is hereby granted, free of charge, to any person or organization
/// obtaining a copy of the software and accompanying documentation covered by
/// this license (the "Software") to use, reproduce, display, distribute,
/// execute, and transmit the Software, and to prepare derivative works of the
/// Software, and to permit third-parties to whom the Software is furnished to
/// do so, all subject to the following:
/// 
/// The copyright notices in the Software and this entire statement, including
/// the above license grant, this restriction and the following disclaimer,
/// must be included in all copies of the Software, in whole or in part, and
/// all derivative works of the Software, unless such copies or derivative
/// works are solely in the form of machine-executable object code generated by
/// a source language processor.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
/// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
/// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
/// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
/// DEALINGS IN THE SOFTWARE.
/// 
//  ****************************************************************************
#ifndef BLNETWORK_H_INCLUDED
#define BLNETWORK_H_INCLUDED
//  Includes *******************************************************************
#include "../../../compiler.h"
#include "BLSocketDef.h"
#include "BLIp.h"

#endif //BLNETWORK_H_INCLUDED
